### PR TITLE
Feature/rename cdapio

### PR DESCRIPTION
**Pull request by chtyim**

### CODE REVIEW

**Review by CuriousVini — APPROVED** [review]
lgtm 👍 

Do we also need to change link in ReadMe: https://github.com/cdapio/common/blob/develop/common-cli/README.rst#examples ?

**Comment by chtyim** [comment]
Updated README

**Comment by chtyim** [comment]
Build already passed prior to README only change

https://builds.cask.co/browse/COM-BAD12

**Review by CuriousVini — APPROVED** [review]
lgtm last commit 👍

**Pull request merged**
